# Generated by Django 4.1.7 on 2023-03-04 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='title',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='name_vac',
            field=models.CharField(default='Пусто', max_length=80, verbose_name='Название вакансии'),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_skill', models.CharField(max_length=80, verbose_name='Название навыка')),
                ('id_vac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vacancies')),
            ],
        ),
    ]
