# Generated by Django 4.1.7 on 2023-03-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_vacancies_title_vacancies_name_vac_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='id_vac',
            new_name='vacancy',
        ),
    ]
