# Generated by Django 4.1.7 on 2023-03-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_id_vac_skills_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterModelOptions(
            name='vacancies',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='skills',
            name='name_skill',
            field=models.CharField(max_length=100, verbose_name='Название навыка'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='name_vac',
            field=models.CharField(default='Пусто', max_length=100, verbose_name='Название вакансии'),
        ),
    ]
