# Generated by Django 4.1.7 on 2023-03-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_skills_options_alter_vacancies_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='url_hh',
            field=models.CharField(default='', max_length=100, verbose_name='Ссылка на вакансию'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='name_vac',
            field=models.CharField(default='', max_length=100, verbose_name='Название вакансии'),
        ),
    ]
